# pubspec.yaml
name: empylo_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.4.8
  dio: ^5.3.3
  hive_flutter: ^1.1.0
  go_router: ^12.1.1
  jwt_decode: ^0.3.1
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mocktail: ^1.0.0
  test: any
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
